### ISSUE TITLE
[Request] Batch API: Return multiple assets from a query

### ISSUE THREAD

**Issue by tracfren** [grafana/iot-sitewise-datasource#115]
Is it possible for a query to return multiple assets? Can the asset variable be a multiselect?

**Comment by taleena** [comment]
**Desired functionality:**
We want to be able to request several properties in a single query. This is useful everywhere but is especially important in annotations

**Suggested solution:**
Select multiple properties in the annotations query (like aggregates in panel query)

**Existing workaround:**
In panels we can write multiple queries. In annotations there is no workaround. We can annotate the timestamp and display the data field. We cannot map anything else

This is 4th in the list of nice to haves.

**Comment by ryantxu** [comment]
Is there an API to return multiple assets?  We are calling:
https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_GetAssetPropertyValue.html

To get multiple assets, we can just add multiple queries -- or am I missing something?

**Comment by jake-bierman** [comment]
Currently having the same problem, We are wanting to show a table with info from multiple assets, but having to create a fixed query for each. using a variable is great when doing templating as we only have one assetid in the variable, but when trying to query for a list of assets dynamically this does not seem possible at the moment.
Since the list of assets will vary over time, the hope is to have a dash variable which will return a list of asset ids, then we could use this variable in the sitewise query to query the property for all assets in one query.

**Comment by nyamad** [comment]
Hello,

AWS has released 3 new `BatchGetAssetProperty*` APIs in 9th of this month.
[Announcing three new APIs for batch data retrieval in AWS IoT SiteWise](https://aws.amazon.com/about-aws/whats-new/2022/05/announcing-new-apis-batch-data-retrieval-aws-iot-sitewise/)

[BatchGetAssetPropertyValue](https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_BatchGetAssetPropertyValue.html) seems to be suitable for explained use cases.

I'd appreciate it if you will support those APIs for query functions.

Thanks,

**Comment by taleena** [comment]
We have documentation on the Batch API. Updating title to better reflect. We still need to scope this effort.
