### ISSUE TITLE
Make auto aggregation more transparent by showing the expected resolution

### ISSUE THREAD

**Issue by taleena** [grafana/iot-sitewise-datasource#120]
Enhancement request on behalf of @tracfren 

Make auto aggregation more transparent by showing the expected resolution in the "Query options" dialog

**Desired functionality:**
We want to use Auto mode but still have control over the resolution by changing the "Max data points". We want the displayed "Interval" to match the actual resolution being retrieved

**Suggested solution:**
We want auto resolution to have a smoother transition between resolutions (see above), and to show what it would do in the "Query options" dialog. Conform to the Grafana standard of (Time range / max data points)

**Existing workaround:**
We need to run the query and see what happens

This is the 2nd item on nice to haves.

**Comment by taleena** [comment]
@tracfren - the workaround seems to be on par with how queries would behave - is there more context behind why this in particular suffers from having to run the query to see what happens?

**Comment by tracfren** [comment]
The problem is you do now know when the auto resolution change will happen (i.e., from raw to 1 minute aggregates) as it it based on the number of data points over the time range. A customer who is looking at raw data and decides to zoom out to see a wider range of raw data may have their aggregation level change on them. They lose context into what they are viewing.

**Comment by katebrenner** [comment]
close as stale
