### ISSUE TITLE
new release 1.4.1 breaks FlowCharting graph

### ISSUE THREAD

**Issue by misiek303** [grafana/iot-sitewise-datasource#145]
After the upgrade from 1.2.6 to 1.4.1 FlorCharting graph broke some of the queries. Some of the queries are not available in the Mapping option -> Apply to column. The Property value is an **INTEGER**. 

**Grafana 9.2.2 version.**

**Before the upgrade**
![Screen Shot 2022-11-02 at 10 25 03 AM](https://user-images.githubusercontent.com/371344/199532777-d5a546bb-b6a2-410f-8555-1edfa0031dde.png)

**After the upgrade**
![Screen Shot 2022-11-02 at 10 26 32 AM](https://user-images.githubusercontent.com/371344/199532932-c5b91eae-1217-4602-998f-eecd26070066.png)

### Also after the upgrade, something else changed. The label of the fields.

**This is how the Pie chart should look, showing the percentage and State text.**
![Screen Shot 2022-11-02 at 10 38 13 AM](https://user-images.githubusercontent.com/371344/199533699-94f764e5-3b93-4a73-b11f-fdd241b92bb1.png)

**And this is what happened after upgrade**
![Screen Shot 2022-11-02 at 10 36 46 AM](https://user-images.githubusercontent.com/371344/199533757-5112c930-2b3a-420d-aae6-6740712f3ddf.png)

Is there any potential fix for that or a known issue that is going to be addressed soon?
Thanks

**Comment by ryantxu** [comment]
Interesting... can you take a snapshot and attach it to this issue?  https://grafana.com/blog/2022/10/17/grafana-9.2-release-troubleshooting-grafana-panels-with-a-new-support-feature/

**Comment by taleena** [comment]
Also, what version of Grafana are you on (and did that remain the same)?

**Comment by misiek303** [comment]
Hi I mentioned in the post. It is 9.2.2 version. Thanks

> 

That links takes me to post, not an issue. Also what snapshot would you like me to attach. I don't have anything besides I already snapped :). Thanks

**Comment by taleena** [comment]
Got it, so you used 9.2.2 for both 1.2.6 and 1.4.1 versions of TwinMaker.

Ha, I got similarly confused! That post shows you how to make a snapshot, it's a new feature in 9.2. Once done, see if you can attach that to this same issue.

**Comment by misiek303** [comment]
Can I help with anything to troubleshoot this issue?

**Comment by leeoniya** [comment]
@ryantxu is refering to a debug snapshot generated from the Panel > More > Get Help menu. these snapshots are self-contained and do not have a url. they can be attached to this issue. please see the video in link https://github.com/grafana/iot-sitewise-datasource/issues/145#issuecomment-1300941059

**Comment by misiek303** [comment]
Thanks. Files are attached and marked 1.2.6v and 1.4.1v
[1.4.1v-debug-Floor Plan v1-2022-11-11 22 42 35.json.txt](https://github.com/grafana/iot-sitewise-datasource/files/9994116/1.4.1v-debug-Floor.Plan.v1-2022-11-11.22.42.35.json.txt)
[1.2.6v-debug-Floor Plan v1-2022-11-11 22 32 42.json.txt](https://github.com/grafana/iot-sitewise-datasource/files/9994117/1.2.6v-debug-Floor.Plan.v1-2022-11-11.22.32.42.json.txt)

**Comment by misiek303** [comment]
Thanks, @ryantxu is there anything else I can provide ?

**Comment by toddtreece** [comment]
@misiek303 I believe this was caused by the change to wide time series to support alerting in #135. Adding the `Prepare time series` transformation and using the `Long time series` format seems to fix the issue for me in the panel options. Could you try adding that and let us know if that fixes your dashboard?

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/360020/204646325-1cf4f8c2-f561-4a76-a20e-d86ea89366a0.png">

@ryantxu I wasn't able to get the flowchart viz to load with either of the attached examples, but it seems like it could be an issue with angular and/or the debug snapshot tool.

**Comment by misiek303** [comment]
Indeed it fixes showing up all metrics in the drop-down of the FlowCharting plugin. But it breaks the string-type data.
There is info about strings: "String values are represented as separate fields rather than as labels", but I am not sure how it works.

![Screenshot 2022-11-29 at 3 27 26 PM](https://user-images.githubusercontent.com/371344/204652055-ddb8e028-ca9a-49fc-8ccb-46c67f103bc2.png)

No String values are shown

![Screenshot 2022-11-29 at 3 28 03 PM](https://user-images.githubusercontent.com/371344/204652071-29302faa-20ef-4d4d-806e-1b9d414412c9.png)

**Comment by toddtreece** [comment]
@misiek303 i see what's going on here. the transformation is expecting all queries to have at least one time column and one numeric column, but it seems like some of your queries are returning only time and string columns

@ryantxu any thoughts on how to mix the two types of queries since we can't target individual queries with transformations? i guess we could add an option to format the query in the editor?

**Comment by misiek303** [comment]
Hi. Are you working on this issue? can I get an update?

**Comment by toddtreece** [comment]
`v1.5.1` includes a change to allow selection for `Table` and `Time series` formats, and defaults to the pre-1.4.x `Table` format. please let us know if you see issues after upgrading to 1.5.1
