### ISSUE TITLE
[Request]: Ability to filter assets on Asset Name

### ISSUE THREAD

**Issue by taleena** [grafana/iot-sitewise-datasource#154]
Filing this on behalf of a feature request.

Based on the information provided on [the plugin page](https://grafana.com/grafana/plugins/grafana-iot-sitewise-datasource/), it looks like the assets are being pulled and identified by their ID numbers, which are randomly generated UUIDs. Therefore, users are unable to filter using visible Asset Name, rather than Asset IDs.

**What are you really trying to do?**
Filter specific assets using filters or regex that gets applied to visible Asset Name.

**Context and constraints**
This is an important issue and blocker for the user.

**Describe what you've already tried and where it falls short**

1. Create IoT Sitewise assets
2. Create Sitewise plugin
3. Create dashboard
4. Create variable in dashboard using Sitewise data source
5. Select "List assets" query type (eg Asset 1, Asset 2, Asset 3) 
6. Input regex to attempt to filter the returned assets (eg only show Asset 2)
7. See that this does not return the expected results as it is filtering on ID, not name

Example, if I have 4 assets:

A_ABC1_XYZ1
A_ABC1_XYZ2
B_ABC2_XYZ1
C_ABC1_XYZ1

Tried to pull only the last two specifically using the full names, (B_ABC2_XYZ1|C_ABC1_XYZ1), but the result returned was "None".

**Additional context**
The assumptions of the regex functionality: It should help filter data containing some constant info/schema. UUIDs are generated totally randomly, so this functionality does not work.
The user wants to filter their data on a constant field (such as asset name) rather than a random string such as the ID.

**Environment**
- Grafana version: Amazon Managed Grafana v8.4.7
- Data source version: SiteWise v1.4.1
- OS Grafana is installed on:
- User OS & Browser:
- Product or feature area: 
- Impacted routes: 
- Others:

**Comment by sarahzinger** [comment]
Just wanted to say I was able to recreate this. However I think this is more a bug with grafana than a sitewise feature.

I was able to use our test credentials which returned back an asset that looked something like this:
```
{ name: "Demo ..." id: "6edf..."}
```

when I then tried to use a template variable for that info and filter it with a regex, /De/ did not return any results in the preview value but /6e/ did which is confusing because the "Preview of values" returns the name of the value not the id

![Screenshot 2023-03-07 at 1 59 11 PM](https://user-images.githubusercontent.com/6620164/223523913-96c7ba8d-32b7-44de-aa02-318abdc79f23.png)
![Screenshot 2023-03-07 at 1 59 22 PM](https://user-images.githubusercontent.com/6620164/223523915-0cb5f387-c9bd-40a3-acdc-ec7119f5196c.png)

This feels like a fixable problem, although I'm not sure where the fix would go or what exactly it would look like. I did find [this](https://github.com/grafana/grafana/issues/44490) which appears to be the same issue for Azure.

I think it seems reasonable to keep this ticket open in this repo for now, although possibly whoever takes this issue might want to move it to main grafana. I might also recommend that included in this ticket is documenting a bit more the VariableEditor API so that future plugin developers can also learn how this functionality works for the future and what format data should be sent in for the regex to work properly, along with any limitations.

**Comment by idastambuk** [comment]
I had to revert the commit that closed this because it broke something variable interpolation. After some investigation, I would agree with @sarahzinger that it's a grafana issue, so I opened a feature request. 
It's possible that variable work isn't under active development due to Scenes and this might be supported out of the box there, but I don't know much about it.
