### ISSUE TITLE
Migrate to CustomVariableSupport

### ISSUE THREAD

**Issue by idastambuk** [grafana/iot-sitewise-datasource#233]
**What happened**:
As described [here](https://github.com/grafana/iot-sitewise-datasource/pull/229), we need to investigate why this happens and reimplement custom variable support. 

> we need to use metricFindQuery for query variable support, otherwise the variable object resolves to {text: "Demo Wind Farm Asset", value "Demo Wind Farm Asset"}, which is not what we want, since when they are selected in dashboards, their IDs are sent in different types of queries and not their names.
> 
> The only time we would need the names is when the variables are being filtered by regex like https://github.com/grafana/iot-sitewise-datasource/issues/154. However, the solution for this in the original commit is just a consequence of the values being the same as names, and not a proper fix.
> I will reopen the original ticket, since we will need to reimplement custom variable support.

We should investigate why the values resolve to `{text: "Demo Wind Farm Asset", value "Demo Wind Farm Asset"}` and not to the assetId. For some reason the variable value in the redux state is equal to its text, for example:
<img width="1079" alt="Screenshot 2023-10-16 at 8 54 51 PM" src="https://github.com/grafana/iot-sitewise-datasource/assets/16140639/b684f4e6-08b0-4b2c-9729-48a894992577">

**What you expected to happen**:
The variable value should have value of the id. 
**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version:10.2.0
- Plugin version:1.10.0
- OS Grafana is installed on:
- User OS & Browser:
- Others:

**Comment by iwysiu** [comment]
From investigating the linked athena issue, the problem seems to be that CustomVariableSupport expects data frames with `text` and `value` fields. I suspect that the query we're returning doesn't have those fields, so instead it takes the first field (in the example case the name) and uses it for both values. If that is the case, we're going to have to process the results (maybe write resource handlers for them) to get them into the correct formats to be used as variables
