### ISSUE TITLE
Support propertyAlias to fetch data

### ISSUE THREAD

**Issue by tracfren** [grafana/iot-sitewise-datasource#98]
SiteWise GET APIs for fetching SiteWise data (i.e. https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_GetAssetPropertyValueHistory.html) support propertyAlias as an alternative to using assetId + propertyId.

**Comment by atifali** [comment]
how do we get the `assetProperty` description from just using the `propertyAlias`?

looks like we do need the `propertyId` for this to work:
https://docs.aws.amazon.com/iot-sitewise/latest/APIReference/API_DescribeAssetProperty.html

currently all responses use the `assetProperty` description to properly format the query results to frames.

**Comment by macrovve** [comment]
There is no way to get propertyId by alias from the API. 
May I ask why do you need the property id?

**Comment by atifali** [comment]
well we need the `assetProperty` description to set the `dataType` for conversion to frames. see: https://github.com/grafana/iot-sitewise-datasource/pull/99#issuecomment-881043402 

and it looks like currently the SiteWise API only supports `DescribeAssetProperty` with both `assetId` and `propertyId` as params. is there a way to run `DescribeAssetProperty` with `propertyAlias' as the only param? seems like a useful thing to have, since most other queries also have that option

**Comment by macrovve** [comment]
Currently, there is no such api. 😞

**Comment by atifali** [comment]
for now we have implemented some ad-hoc `dataType` inference:
https://github.com/grafana/iot-sitewise-datasource/pull/99#issuecomment-893116539

but i do still think having the functionality in the api i mentioned would go far and be very useful. keep us updated on that 🙂
